# Generated by Django 4.0.5 on 2022-09-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MWMapp', '0008_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='adhar',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/CustomerProfilePic/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='eye',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/CustomerProfilePic/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fitness',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/CustomerProfilePic/'),
        ),
    ]
