# Generated by Django 4.0.5 on 2022-09-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MWMapp', '0009_alter_product_adhar_alter_product_eye_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='adhar',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='eye',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fitness',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/'),
        ),
    ]
