# Generated by Django 4.0.5 on 2022-09-25 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MWMapp', '0011_alter_product_adhar_alter_product_eye_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='adhar',
            field=models.ImageField(default='1', upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='eye',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='fitness',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/'),
            preserve_default=False,
        ),
    ]
