# Generated by Django 4.0.5 on 2022-10-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MWMapp', '0012_alter_product_adhar_alter_product_eye_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaintin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaintsub', models.CharField(max_length=200, null=True)),
                ('complaintdes', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
